export default Object.freeze({
    ACCOUNT_FORM: "AccountForm",
    ANNOUNCEMENTS: 'Announcements',
    ANNOUNCEMENT_DETAILS: 'AnnouncementDetails',
    CONTACTS: 'Contacts',
    HOME: 'Home',
    INVOICES: "Invoices",
    INVOICE_DETAILS: "InvoiceDetails",
    LOGIN: 'Login',
    MENU: 'Menu',
    MODE_OF_PAYMENTS: 'ModeOfPayments',
    PAYMENTS: 'Payment',
    PAYMENT_DETAILS: 'PaymentDetails',
    PAYMENT_FORM: 'PaymentForm',
    PAYMENT_RECEIPT: 'PaymentReceipt',
    SLOTS: "Slots",
    SLOT_DETAILS: 'SlotDetails',
    SLOT_LOCATOR: ' SlotLocator',
    SURVEY_FORM: ' SurveyForm',
});
